var darmok = require("darmok");

// county names from wisconsin and minnesota
var generator = darmok.markov([
    "Ah-gwah-ching",
    "Anoka",
    "Bejou",
    "Bemidji",
    "Bena",
    "Chanhassen",
    "Chaska",
    "Chengwatana",
    "Chippewa",
    "Chisago",
    "Chokio",
    "Cohasset",
    "Cokato",
    "Dakota",
    "Eyota",
    "Hackensack",
    "Hanska",
    "Hokah",
    "Isanti",
    "Kanabec",
    "Kandiyohi",
    "Kasota",
    "Keewatin",
    "Koochiching",
    "Mahnomen",
    "Manomin",
    "Mahtomedi",
    "Mahtowa",
    "Mankato",
    "Menahga",
    "Mendota",
    "Minneiska",
    "Minnetonka",
    "Nashwauk",
    "Nisswa",
    "Ogema",
    "Okabena",
    "Onamia",
    "Otsego",
    "Owatonna",
    "Pokegama",
    "Shakopee",
    "Squaw Lake",
    "Wabasso",
    "Waconia",
    "Wadena",
    "Wahkon",
    "Waseca",
    "Waubun",
    "Wayzata",
    "Winona",
    "Minnehaha Creek",
    "Lake Bemidji",
    "Lake Winnibigoshish",
    "Chippewa",
    "Iowa",
    "Kenosha",
    "Kewaunee",
    "Manitowoc",
    "Menominee",
    "Milwaukee",
    "Oneida",
    "Oshkosh",
    "Outagamie",
    "Ozaukee",
    "Waukesha",
    "Waupaca",
    "Waushara",
    "Winnebago"
], 2);

module.exports.get = function() {
    return generator.generate(32);
};
